- name: Initialize global results
  set_fact:
    global_results: |
      {{
        {
          'results': {
            item: {
              'checks': {}
            }
          }
        }
      }}
  run_once: yes
  delegate_to: localhost
  with_items: "{{ group_names }}"

- name: Set Global Results
  set_fact:
    global_results: |
      {{ global_results | combine(
        hostvars[item]['results']|default({}), recursive=True)
      }}
  with_inventory_hostnames:
    - all
  run_once: yes
  delegate_to: localhost

- name: Post Global Results To ARA
  ara_record:
    key: "trento-results"
    value: "{{ global_results }}"
    type: json
  run_once: yes
  delegate_to: localhost
  changed_when: false
  register: record

- name: Print results
  debug:
    msg: '{{ record.value }}'
    verbosity: 1
  run_once: yes
  delegate_to: localhost
