apiVersion: v2
name: trento-server
description: The trento server chart contains all the components necessary to run a Trento server.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates
version: 0.1.0

maintainers:
  - name: trento-project
    email: trento-project@suse.com
    url: https://trento-project.io

dependencies:
  - name: trento-web
    version: ">0.0.0"
    condition: trento-web.enabled
  - name: trento-runner
    version: ">0.0.0"
    condition: trento-runner.enabled
  - name: ara
    version: ">0.0.0"
    condition: ara.enabled
  - name: consul
    version: "~0.32.1"
    repository: https://helm.releases.hashicorp.com
    condition: consul.enabled
  - name: postgresql
    version: ~10.1.4
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
