### Global Values if any ###
global: {}

### Sub Charts Specific Values ###
trento-web:
  enabled: true

trento-runner:
  enabled: true

ara:
  enabled: true

consul:
  enabled: true
  server:
    bootstrapExpect: 1
    replicas: 1
    exposeGossipAndRPCPorts: true

postgresql:
  enabled: true
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlDatabase: "trento"
