---

- name: Set Test ID
  set_fact:
    test_id: '1.4.1'

- name: "{{ test_id }}.check"
  shell: |
    # if no Azure Fence Agent exit, with a pass
    cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1 || exit 0
    # Check that following match expected, exit with error if any do not
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_monitor_retries']" | grep -oP 'value="\K[^"]+') != "{{ expected[test_id + '.pcmk_monitor_retries'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_action_limit']" | grep -oP 'value="\K[^"]+') != "{{ expected[test_id + '.pcmk_action_limit'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='power_timeout']" | grep -oP 'value="\K[^"]+') != "{{ expected[test_id + '.power_timeout'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_reboot_timeout']" | grep -oP 'value="\K[^"]+') != "{{ expected[test_id + '.pcmk_reboot_timeout'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/operations/op [@name='monitor']" | grep -oP 'interval="\K[^"]+') != "{{ expected[test_id + '.monitor_interval'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/operations/op [@name='monitor']" | grep -oP 'timeout="\K[^"]+') != "{{ expected[test_id + '.monitor_timeout'] }}" ]] && exit 1
    exit 0 
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
