global:
  postgresql:
    postgresqlUsername: "postgres"
    postgresqlPassword: "postgres"
    postgresqlDatabase: "trento"

postgresql:
  service:
    type: NodePort
    nodePort: 32432
    
trento-server:
  consul:
    enabled: false