global:
  postgresql:
    postgresqlUsername: "postgres"
    postgresqlPassword: "postgres"
    postgresqlDatabase: "trento"

postgresql:
  service:
    type: NodePort
    nodePort: 32432
  initdbScripts:
    init.sql: |
      CREATE DATABASE trento_test;
    
trento-server:
  consul:
    enabled: false