name: Lint and Test Helm charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed)
      #     if [[ -n "$changed" ]]; then
      #       echo "::set-output name=changed::true"
      #     fi

      - name: Add repositories
        run: | 
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add hashicorp https://helm.releases.hashicorp.com

      - name: Run chart-testing (lint)
        run: ct lint --charts packaging/helm/trento-server

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        #if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch main --charts packaging/helm/trento-server --helm-extra-args "--timeout 10m"
 